### ISSUE TITLE
issues/copy: specify target repo based on mapping

### ISSUE THREAD

**Issue by Skaty** [nus-cs2103/hubatch#3]
## Current Behaviour

When the `copy` function is executed, the issues are copied to a single target repository. There is currently no support for multiple repositories. 

## New Behaviour

The `copy` function will be able to:
- [x] Copy issues to different organisations (subject to permissions)
- [x] Vary the destination repository based on the image of the mapping.

### New Command Structure

- `torepo` argument - modify to take in a repository name in `org/repo` format. Additionally, the argument may be expressed as a Python 3 format string (e.g. `org{}/repo`). The replacement field will be replaced with the mapping's output.

**Comment by damithc** [comment]
@Skaty we still need the old behavior for final testing. This one is an additional functionality to be used for mock testing in week 11.

**Comment by Skaty** [comment]
@damithc As stated above, the `torepo` format "may" be expressed as a Python 3 format string. As such, the format string is entirely optional and if omitted, would result in the old behaviour.
